services:
  api:
    build: .
    image: ml-api:v1
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ml/saved_model:/app/ml/saved_model
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    depends_on:
      - api    